name: miplib

dependencies:
  - python=2.7
  - numpy=1.13.0
  - scipy
  - h5py
  - SimpleItk
  - matplotlib
  - pyculib
  - pandas
  - pims
  - jpype1
  - notebook
  - scikit-image
  - cudatoolkit=7.5
  - numba=0.39


channels:
  - anaconda
  - conda-forge
  - simpleitk

