name: miplib

dependencies:
  - python=3.6
  - numpy=1.14.5
  - scipy
  - h5py
  - SimpleItk
  - matplotlib
  - numba=0.39
  - pyculib
  - pandas
  - pims=0.4.1
  - jpype1=0.7.5
  - notebook
  - scikit-image
  - cudatoolkit=7.5
  - pip
  - pip:
    - psf
    - miplib >= 1.0.5


channels:
  - anaconda
  - conda-forge
  - simpleitk
  - numba

