name: miplib3

dependencies:
  - python=3.6
  - numpy
  - scipy
  - h5py
  - SimpleItk
  - matplotlib
  - numba=0.39
  - pyculib
  - pandas
  - pims
  - jpype1
  - notebook
  - scikit-image

channels:
  - anaconda
  - conda-forge
  - simpleitk

